server:
  port: 8090

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/exoapp}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:admin}
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
        id:
          new_generator_mappings: true


